#!/usr/bin/env python

import rospy

from std_msgs.msg import String

from std_msgs.msg import UInt32



  

def callback(data):

	rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)

       

def listener():

   

 

	rospy.init_node('node_c', anonymous=True)

	

	rospy.Subscriber("topic_a", String, callback)

	rospy.Subscriber("topic_b", UInt32, callback)



	

	

	

	rospy.spin()

  

if __name__ == '__main__':

	listener()
