#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from std_msgs.msg import UInt32
current = 0
def callback(data):
         rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)
   
def listener():
	global current
	
	
   	rospy.init_node('node_b', anonymous=True)
	pub = rospy.Publisher('topic_b', UInt32, queue_size=10)
	rospy.Subscriber("topic_a", String, callback)
	
	rate = rospy.Rate(10) # 10hz
	while not rospy.is_shutdown():
		current=current+1
		rospy.loginfo(current)
		pub.publish(current)
		rate.sleep()
 
if __name__ == '__main__':
       listener()
