#!/usr/bin/env python
import rospy
from message_assignment.msg import MyMessages

def testing_msgs_a():
	pub=rospy.Publisher('mymsg_a',queue_size=10)
	rospy.init_node('mymsgs_a',anonymous=True)
	rate=rospy.Rate(10)#10hz

	while not rospy.is_shutdown():
		hello_str=MyMessages()
		rospy.loginfo(hello_str)
		pub.publish(hello_str)
		rate.sleep()

if __name__=='main':
	testing_msgs_a()

