#!/usr/bin/env python
import rospy
import random
from message_assignment.msg import MyMessages
import rospy
from nav-msgs.msg import Odometry

def callback(data):
	rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data) 
	rospy.loginfo(rospy.get_caller_id()+"I heard %s",data.message)

def callbackOdom(msg):
	rospy.loginfo(rospy.get_caller_id()+"x; %s",msg.pose.pose.position.x)
	rospy.loginfo(rospy.get_caller_id()+"y: %s",msg.pose.pose.position.y)

def testing_msgs_b();
	rospy.init_node('testing_msgs_b',anonymous=True)
 	rospy.Subscriber("mymsg_a",	MyMessages,callback)
	rospy.Subscriber("odom",Odometry,callbackOdom)
	rospy.spin()

if_name_=='--main--';
testing_msgs_b()
